### ISSUE TITLE
vue3 中 header插槽 报错 Non-function value encountered for default slot. Prefer function slots for better performance. 

### ISSUE THREAD

**Issue by coderWenzi** [keno-lee/vue-tiny-virtual-list#1]
<template #header>
            我是头部的内容
 </template>    控制台警告内容是Non-function value encountered for default slot. Prefer function slots for better performance.

**Comment by coderWenzi** [comment]
这个是我的代码  <template #header>
            
            <div class='load-toolbar pointer'>
              <span v-if='loadConfig.status == 0'> 正在加载数据中 ... </span>
              <span v-else-if='loadConfig.status == 1' @click='onLoadTalk'> 查看更多消息 ... </span>
              <span v-else class='no-more'> 没有更多消息了 </span>
            </div>
          </template>

**Comment by coderWenzi** [comment]
我的代码如下
<template #header>
  我是头部的内容
</template>

**Comment by keno-lee** [comment]
> <template #header> 我是头部的内容 控制台警告内容是Non-function value encountered for default slot. Prefer function slots for better performance.

可以提供一下版本信息吗？这个问题在v1.2.x中解决过。或者直接使用v1.3.0
