### ISSUE TITLE
scrollToBottom() 似乎不是每次都能完全滚动到底部

### ISSUE THREAD

**Issue by coderWenzi** [keno-lee/vue-tiny-virtual-list#2]
virtualListRef.value.scrollToBottom()     vue3 中使用  似乎不是每次都能滚动到底部

**Comment by keno-lee** [comment]
在v1.3.0中已经修复该问题了，感谢反馈
<img width="833" alt="image" src="https://github.com/keno-lee/vue-tiny-virtual-list/assets/35287326/e09222d1-5ff0-4f35-b604-9d622384cce0">

**Comment by keno-lee** [comment]
> virtualListRef.value.scrollToBottom() vue3 中使用 似乎不是每次都能滚动到底部

在v1.3.0中已经修复该问题了，感谢反馈

![image](https://github.com/keno-lee/vue-tiny-virtual-list/assets/35287326/ffced5fd-e111-4f4a-b6de-e7e14551a005)
