### ISSUE TITLE
建议暴露index

### ISSUE THREAD

**Issue by leonhu0710** [keno-lee/vue-tiny-virtual-list#3]
建议在模板 slot 中 暴露数据项  的  index, 目前只暴露了 itemData,在有些场景还是需要 index 的

**Comment by keno-lee** [comment]
> 建议在模板 slot 中 暴露数据项 的 index, 目前只暴露了 itemData,在有些场景还是需要 index 的

好的。感谢建议，最近会更新一版本 useVirtualList 的高级用法，顺带把index加进去

**Comment by keno-lee** [comment]
> 建议在模板 slot 中 暴露数据项 的 index, 目前只暴露了 itemData,在有些场景还是需要 index 的

在v1.3.1中已经新增index参数，并发布了v1.4.0-beta版本，使用高阶用法用来布局table、合并单元格等复杂布局，欢迎体验

**Comment by leonhu0710** [comment]
厉害，膜拜大佬



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月6日(周三) 中午11:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [keno-lee/vue-tiny-virtual-list] 建议暴露index (Issue #3)




  
建议在模板 slot 中 暴露数据项 的 index, 目前只暴露了 itemData,在有些场景还是需要 index 的
  
在v1.3.1中已经新增index参数，并发布了v1.4.0-beta版本，使用高阶用法用来布局table、合并单元格等复杂布局，欢迎体验

**Comment by keno-lee** [comment]
> 厉害，膜拜大佬
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年12月6日(周三) 中午11:43 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [keno-lee/vue-tiny-virtual-list] 建议暴露index (Issue #3) 建议在模板 slot 中 暴露数据项 的 index, 目前只暴露了 itemData,在有些场景还是需要 index 的 在v1.3.1中已经新增index参数，并发布了v1.4.0-beta版本，使用高阶用法用来布局table、合并单元格等复杂布局，欢迎体验 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

如果能帮到你，感谢给身边人推广一下。后续还有一个基于虚拟列表，支持合并单元格、分组、树形、万行千列的表格组件。

**Comment by leonhu0710** [comment]
嗯嗯，引入推广到项目组使用了，解决了大数据卡顿痛点，期待新产品



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月7日(周四) 下午4:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [keno-lee/vue-tiny-virtual-list] 建议暴露index (Issue #3)




  
厉害，膜拜大佬
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2023年12月6日(周三) 中午11:43 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [keno-lee/vue-tiny-virtual-list] 建议暴露index (Issue #3) 建议在模板 slot 中 暴露数据项 的 index, 目前只暴露了 itemData,在有些场景还是需要 index 的 在v1.3.1中已经新增index参数，并发布了v1.4.0-beta版本，使用高阶用法用来布局table、合并单元格等复杂布局，欢迎体验 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
如果能帮到你，感谢给身边人推广一下。后续还有一个基于虚拟列表，支持合并单元格、分组、树形、万行千列的表格组件。
